"""add config sets and games to league_matches

Revision ID: 088fdecc7f16
Revises: cdb79dc62c94
Create Date: 2026-05-05 19:14:24.123759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '088fdecc7f16'
down_revision: Union[str, Sequence[str], None] = 'cdb79dc62c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_sets', sa.Integer(), server_default=sa.text('3'), nullable=False))
        batch_op.add_column(sa.Column('config_games', sa.Integer(), server_default=sa.text('6'), nullable=False))

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_games', sa.Integer(), server_default=sa.text('6'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('config_games')

    with op.batch_alter_table('league_matches', schema=None) as batch_op:
        batch_op.drop_column('config_games')
        batch_op.drop_column('config_sets')

    # ### end Alembic commands ###
