"""empty message

Revision ID: 32a7e29b51e4
Revises: 
Create Date: 2026-05-04 13:44:50.721876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '32a7e29b51e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_j1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_j2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_sets', sa.Integer(), nullable=False),
    sa.Column('puntos_j1', sa.Integer(), nullable=False),
    sa.Column('puntos_j2', sa.Integer(), nullable=False),
    sa.Column('juegos_j1', sa.Integer(), nullable=False),
    sa.Column('juegos_j2', sa.Integer(), nullable=False),
    sa.Column('sets_j1', sa.Integer(), nullable=False),
    sa.Column('sets_j2', sa.Integer(), nullable=False),
    sa.Column('is_tiebreak', sa.Boolean(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('games_j1', sa.Integer(), nullable=False),
    sa.Column('games_j2', sa.Integer(), nullable=False),
    sa.Column('had_tiebreak', sa.Boolean(), nullable=False),
    sa.Column('tiebreak_points_j1', sa.Integer(), nullable=False),
    sa.Column('tiebreak_points_j2', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Integer(), nullable=False),
    sa.Column('was_tiebreak', sa.Boolean(), nullable=False),
    sa.Column('tiebreak_points_j1', sa.Integer(), nullable=False),
    sa.Column('tiebreak_points_j2', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('sets')
    op.drop_table('matches')
    # ### end Alembic commands ###
