"""empty message

Revision ID: cdb79dc62c94
Revises: 32a7e29b51e4
Create Date: 2026-05-04 20:20:11.466832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cdb79dc62c94'
down_revision: Union[str, Sequence[str], None] = '32a7e29b51e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sets_per_match', sa.Integer(), nullable=False),
    sa.Column('games_per_set', sa.Integer(), nullable=False),
    sa.Column('players_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sets_per_match', sa.Integer(), nullable=False),
    sa.Column('games_per_set', sa.Integer(), nullable=False),
    sa.Column('players_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('league_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('leg', sa.Integer(), nullable=False),
    sa.Column('home', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sets_home', sa.Integer(), nullable=False),
    sa.Column('sets_away', sa.Integer(), nullable=False),
    sa.Column('bracket_position', sa.Integer(), nullable=True),
    sa.Column('next_match_id', sa.Integer(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('league_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_matches_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_league_matches_tournament_id'), ['tournament_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_matches_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_league_matches_league_id'))

    op.drop_table('league_matches')
    op.drop_table('tournaments')
    op.drop_table('leagues')
    # ### end Alembic commands ###
